version: '3'
services:
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
  redis:
    image: "redis"
    ports:
     - "6379:6379"
  kafka:
    image: "landoop/fast-data-dev"
    environment:
    - ADV_HOST=127.0.0.1
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081:8081"
      - "8082:8082"
      - "9092:9092"